---

language: node_js

node_js:
  - lts/*

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

cache:
  directories:
    - /tmp/liftoff

matrix:
  include:
    - env: DIST=loki
    - env: DIST=juno

before_install:
  - docker pull ubuntu:16.04

install:
  - npm install @elementaryos/houston

script:
  - houston ci
    --name-appstream com.github.cassidyjames.dippi.desktop
    --name-domain com.github.cassidyjames.dippi
    --name-human Dippi
    --distribution $DIST
